### ISSUE TITLE
add a code of conduct

### ISSUE THREAD

**Issue by AaronLasseigne** [orgsync/active_interaction#292]
It seems reasonable that we lay out expectations of behavior when interacting with this project.

I suggest: http://todogroup.org/opencodeofconduct/

cc: @tfausak

**Comment by tfausak** [comment]
I am not opposed to adopting a code of conduct. However I wonder if it is necessary. How are our existing [contribution guidelines](https://github.com/orgsync/active_interaction/blob/v2.0.1/CONTRIBUTING.md) insufficient for laying out expectations?

**Comment by tfausak** [comment]
If we do adopt a code of conduct, the TOGO Group's looks good for the most part. I do have some nits to pick with it.

1. I would argue that this section could be abused on our part by banning people for being angry:

  > Anyone who violates this code of conduct may be banned from the community.
  >
  > Our open source community strives to: [...]
  >
  > - Be respectful: Not all of us will agree all the time, but disagreement is no excuse for poor behavior and poor manners.

2. I think I see what this section is getting at, but it is necessary to discriminate based on technical ability in order to keep this project in a state that we are happy with. If you are not technically able to meet the existing contribution guidelines, we will reject your pull request. (That being said, you shouldn't be attacked or belittled or anything of the sort, which is what I think this section means.) 

  > Although this list cannot be exhaustive, we explicitly honor diversity in [...] technical ability. We will not tolerate discrimination based on any of the protected characteristics above, including participants with disabilities.

3. In my opinion, reasonably escalating issues is important. I don't want to be a part of another #DongleGate or #OpalGate. Which is why I take issue with the "Reporting Issues" section; it does not attempt to discourage publicly shaming people for perceived bad behavior.

  > If you experience or witness unacceptable behavior—or have any other concerns—please report it by contacting us via [CONTACT].

Those minor issues aside, I agree with it.

**Comment by tfausak** [comment]
We talked about this out of band. I think we will adopt a code of conduct. The only question I have now is: Do we add `CODE_OF_CONDUCT.md` to this repository, or do we link to somewhere else from `README.md` and/or `CONTRIBUTING.md`?

**Comment by AaronLasseigne** [comment]
There have been some changes to the default wording of a few of the CoCs out there. We should re-evaluate them prior to selecting one.

**Comment by AaronLasseigne** [comment]
The Open Code of Conduct is long and some of their recent changes make me less excited about it. I'm leaning toward the [Contributor Covenant](http://contributor-covenant.org/). In particular something similar to the version (slightly modified) used by Opal.

https://github.com/opal/opal/blob/master/CODE_OF_CONDUCT.md

The primary addition being an acknowledgement of what constitutes "representing" a project.

**Comment by AaronLasseigne** [comment]
We're unable to find a code of conduct that seems to fit what we need and the project is still relatively small. Given this we're going to defer the issue to some future date.
