### ISSUE TITLE
hash default: {}

### ISSUE THREAD

**Issue by elfassy** [orgsync/active_interaction#309]
In the readme it says

```ruby
hash :with_defaults,
  default: {} do
    boolean :likes_cookies,
      default: true
  end
# => {:with_defaults=>{:likes_cookies=>true}}
```

But that's giving me `InvalidDefaultError`. Is anyone else getting the same error?

**Comment by elfassy** [comment]
example project to reproduce bug: https://github.com/elfassy/active_interaction_example

**Comment by elfassy** [comment]
```
  hash :params, default: {} do 
    string :name
  end
```
give `ActiveInteraction::InvalidDefaultError`

but
```
  hash :params, default: {} do 
    string :name, default: nil
  end
```
works. Is that the expected behavior?

**Comment by tfausak** [comment]
If the code in your original comment does not work, that is a bug. However it works for me.

``` rb
class Example < ActiveInteraction::Base
  hash :h,
    default: {} do
      boolean :b,
        default: true
    end

  def execute
    inputs
  end
end

Example.run!
# => {:h=>{"b"=>true}}
```

For the code in your latest comment, it is expected to fail. To quote [the documentation](https://github.com/orgsync/active_interaction/blob/v2.1.3/README.md#hash):

> Setting default hash values can be tricky. The default value has to be either `nil` or `{}`. Use `nil` to make the hash optional. Use `{}` if you want to set some defaults for values inside the hash.

So when you set a hash's default to `{}`, you have to set defaults for everything inside the hash as well. Otherwise you would end up with a hash that had `nil` values for inputs that aren't optional. Does that make sense?

**Comment by elfassy** [comment]
it does now, thanks. 

I assumed that 

```
hash :h, 
  default: {} do
      boolean :b, default: true
      string :a
    end
```

would automatically add `default: nil` to `:a`. Might be something to consider but i'll close this for now. Thanks again!

**Comment by tfausak** [comment]
In general we want to encourage you to be explicit. We could try to make the error message better in this case, though.
