### ISSUE TITLE
Allow defining optional inputs in a block

### ISSUE THREAD

**Issue by tfausak** [orgsync/active_interaction#321]
We have talked about grouping optional inputs before in #188. Thanks to #320, I now know that [`with_options`](http://api.rubyonrails.org/classes/Object.html#method-i-with_options) can be used to group optional inputs. So instead of repeating `default: nil` all over the place, you could do this:

``` rb
with_options default: nil do
  boolean :flag
end
```

Since we already depend on ActiveSupport, I think we could endorse this option. In fact, we could provide an `optional` helper method that is a thin veneer over it.

``` rb
optional do # same as `with_options default: nil do`
  boolean :flag
end
```

I think this could be a nice addition to our API. I tend to group up my optional inputs anyway. On the other hand, if this is possible through ActiveSupport, maybe we should just suggest using that and avoid adding more to the already huge base class.

What do you think, @AaronLasseigne?

**Comment by tfausak** [comment]
I'm leaning toward documenting `with_options` and not adding an `optional` method to the class. It seems like the cleanest way to do it.

**Comment by jwoertink** [comment]
I agree. Just documenting is probably the best way. Just a quirky note about it that I learned. 

```ruby
class MyInteraction < ActiveInteraction::Base
  string :thing
  integer :number, default: nil
  validates :thing, presence: true
  with_options if: :something? do |r|
    r.validates :number, presence: true
  end
  validate :custom_thing

  private

  def custom_thing
    false
  end
  def something?
    true
  end
end
```

In case the order of the validations matter for any reason, or you're trying to test that validations exist, the order of these validations would be `thing`, `custom_thing`, and then if those are all good `number` if `something?` if true.

In my case, I had a spec that said "it should fail and include an error for :thing, and :number", but even though `something?` was true, the `errors` object didn't include `:number` because it stopped checking since `thing` and `custom_thing` both failed.

**Comment by AaronLasseigne** [comment]
I don't see a need to wrap it. The `with_options` method should suffice.

**Comment by tfausak** [comment]
Alright, I'll go with documentation. 

@jwoertink that ordering is strange, but I don't think we need to document it. That's purely ActiveSupport's fault.
