### ISSUE TITLE
Problem with ActionController::Parameters in Rails

### ISSUE THREAD

**Issue by mits87** [orgsync/active_interaction#379]
Hi,

I use active_interaction in my Rails project and I have big problem. I try pass parameters from rails to my interaction class and I can't do this because:

> inputs must be a hash

but rails params are ActionController::Parameters type (not a Hash). 

**application.rb**
`config.action_controller.permit_all_parameters = true`

**users_controller.rb:**
`user = Users::Create.run params[:user]`

Of course I can do something like this:
`user = Users::Create.run params[:user].to_h`

but it is not a best solution.
Is it possible to improve it? 

Best Regards

**Comment by tfausak** [comment]
ActiveInteraction doesn't depend on ActionPack, so we can't (easily) check for `ActionController::Parameters`. We could use [`to_hash`](https://zverok.github.io/blog/2016-01-18-implicit-vs-expicit.html), except that the parameters only implement `to_h`. I don't really want to use `to_h` in this case because you can do weird stuff like `X.run([[:foo, :bar]])`. 

For reference, the check happens on [this line](https://github.com/orgsync/active_interaction/blob/v3.2.0/lib/active_interaction/base.rb#L170).

**Comment by tfausak** [comment]
If you're alright with monkey patching ActiveInteraction, you don't need an input decorator. You could just do this:

``` rb
class ActiveInteraction::Base
  def initialize(inputs = {})
    process_inputs(inputs.to_h.symbolize_keys)
  end
end
```

If you *don't* want to monkey patch it, you could define your own subclass and put it there.

``` rb
class ApplicationInteraction < ActiveInteraction::Base
  def initialize(inputs = {})
    super(inputs.to_h)
  end
end
```

That's the better way to go.

**Comment by mits87** [comment]
hmm almost... initialize is private method in ActiveInteraction::Base class so I can't override it.

**Comment by tfausak** [comment]
`initialize` is not private. Even if it was, you could override it. 

``` rb
require 'active_interaction' # 3.2.0
require 'action_controller' # 5.0.0.1

class ActiveInteraction::Base
  def initialize(inputs = {})
    p :initialize
    process_inputs(inputs.to_unsafe_h.symbolize_keys)
  end
end

class Example < ActiveInteraction::Base
  boolean :flag

  def execute
    inputs
  end
end

Example.run!(ActionController::Parameters.new(flag: true))
# :initialize
# => {:flag=>true}
```

**Comment by mits87** [comment]
Thank You.
