### ISSUE TITLE
Block in set_callback

### ISSUE THREAD

**Issue by lulalala** [orgsync/active_interaction#382]
Typing the example from: https://github.com/orgsync/active_interaction/pull/195#issuecomment-44348035

```
class Interaction < ActiveInteraction::Base
  date :birthday,
    default: nil

  set_callback :validate, :before,
    if: 'birthday.blank?',
    prepend: true do
      self.birthday = nil
    end

  def execute
    inputs
  end
end
```

Seems this wouldn't work in rails console, seems the statement does not finish yet. The problem seems to be on the `if`.

Another problem, beside the `if` is that when I made a similar example:

```
class Interaction < ActiveInteraction::Base
  date :birthday, default: nil

  set_callback :validate, :before, prepend: true, lambda { self.birthday = nil }

  def execute
    inputs
  end
end
```

Would give me:

> SyntaxError: (irb):129: syntax error, unexpected '\n', expecting =>

Once I remove the `prepend` argument then it would work.

**Comment by tfausak** [comment]
I'm not sure exactly what the problem is with the first one. You can try using the other hash syntax.

``` rb
# instead of this
if: foo
# do this
:if => foo
```

For the second one, there are two problems. `set_callback` doesn't take a lambda, it takes a block. And Ruby's precedence is weird, so you have to use `do ... end` instead of `{ ... }`.

``` rb
set_callback :foo, :bar, do
  ...
end
# or if you really want curly brackets, you can add parentheses
set_callback(:foo, :bar) { ... }
```

**Comment by lulalala** [comment]
Thanks! Should I update the readme about the 2nd issue?

**Comment by tfausak** [comment]
Oh, I forgot the README uses that style. And apparently `lambda` and `->` do the right thing in terms of precedence. 

The actual problem is that the options hash has to be surrounded with curly brackets. You don't have to do that when the options hash is the last argument, but in this case the last argument is a lambda.

``` rb
set_callback :foo, :bar, { baz: :qux }, -> { ... }
```

If you use a regular block instead of a lambda, you don't need the curly brackets.

``` rb
set_callback :foo, :bar, baz: :qux do
  ...
end
```

As far as I know, all the examples in the README work. If any of them don't, that's a bug. But these problems you're hitting are intricacies of Ruby; they don't have anything to do with ActiveInteraction specifically.

**Comment by lulalala** [comment]
Thanks! Should have realized that.

So that leaves us with the first issue. I'll try testing other Ruby versions then.

**Comment by lulalala** [comment]
Can confirm that I can't have an `if` or `else` key. And this is not a bug particular to ActiveInteraction. I'll see if this is in the Ruby bug tracker or file one if it isn't. Cheers~
