### ISSUE TITLE
Integer filter handles strings unexpectedly

### ISSUE THREAD

**Issue by ngan** [orgsync/active_interaction#386]
Not sure if bug or feature:

When I use the `integer` filter and a string is passed in, the value is coerced into an integer using Ruby's Integer coercion.  However, we get situations like this:

```
2.0.0-p645 :002 > Integer("07")
 => 7
2.0.0-p645 :003 > Integer("08")
ArgumentError: invalid value for Integer(): "08"
```

This is quite unexpected. I would imagine either it always errors or always succeeds. I know this is Ruby and not really ActiveInteraction...but was wondering if we should continue to use `Integer(X)` for conversion.

**Comment by tfausak** [comment]
I think this is a bug. Even though this is the expected behavior of [`Integer`](http://ruby-doc.org/core-2.3.1/Kernel.html#method-i-Integer), we don't explicitly call it out anywhere in our documentation. 

We could add a `base` option to the integer filter for the second argument to `Integer`. Setting that to `10` would make the value `'08'` convert as you expect.
