### ISSUE TITLE
Predicate methods and its confusion

### ISSUE THREAD

**Issue by ngan** [orgsync/active_interaction#394]
Got bit by this the other day, then I saw in the docs:
> This can be confusing for boolean inputs. If you have some boolean input foo, then the actual value of that input is available through foo. The associated predicate method, #foo?, will tell you if that value is not nil. So it will only be false if the input is optional and happens to be nil.

I'd like to propose a few things:
- Only generate predicate methods for `boolean` inputs.
- Predicate methods should return the value of the boolean the confusion stuff up there ^

I notice that I don't really use predicate methods for other input types...

**Comment by tfausak** [comment]
We've had input predicates for a while (#102), but they have caused problems before (#367). I feel like [our current documentation](https://github.com/orgsync/active_interaction/blob/v3.4.0/README.md#predicates) says it well:

> ActiveInteraction creates a predicate method for every input defined by a filter. So if you have an input called `foo`, there will be a predicate method called `#foo?`. That method will tell you if the input was given (that is, if it was not `nil`).

I think it would be more confusing if the predicates only worked on `boolean` inputs. Plus, there would be no difference between `foo` and `foo?`. Why have both?

Similarly, changing the return value for just booleans would be difficult to explain. "It returns `false` if the input is `nil`, `true` otherwise. Except for booleans, in which case it returns the value. Unless the value is `nil`, in which case it returns `false` (?)."

**Comment by ngan** [comment]
> Similarly, changing the return value for just booleans would be difficult to explain. "It returns false if the input is nil, true otherwise. Except for booleans, in which case it returns the value. Unless the value is nil, in which case it returns false (?)."

I would definitely not what to do this.

> I think it would be more confusing if the predicates only worked on boolean inputs. Plus, there would be no difference between foo and foo?. Why have both?

You're right, it would be inconsistent. I suppose I find the way ActiveRecord handles predicate methods more consistently: http://blog.plataformatec.com.br/2012/05/active-record-attribute-method/

**Comment by tfausak** [comment]
The motivating case for ActiveInteraction's predicate methods is something like this:

``` rb
boolean :subscribed, default: nil
def execute
  user.subscribed = subscribed if subscribed?
```

That is, only update an attribute if it's not `nil`. That way you can either leave the field alone or update to a new value. If we went with ActiveRecord's semantics, you wouldn't be able to do that with the predicate method. You'd have to do something like this:

``` rb
user.subscribed = subscribed? unless subscribed.nil?
# or: if subscribed.present?
# or: unless subscribed.blank?
```

**Comment by ngan** [comment]
I see what you mean. But I wonder if you look into your interactions, how often do you really do that?

```ruby
user.subscribed = subscribed if subscribed?
```

We have tons of interactions and we don't have such a thing. I think it's because we simply all just do:
```ruby
user.subscribed = subscribed
```
If it's `nil`, then it'll just get reassigned as `nil`.  I notice the only times we use predicate methods are for booleans:

```ruby
boolean :subscribed, default: false
def execute
  if subscribed
    # send email
  end
```

Would be cool if we could do this instead:
```ruby
boolean :subscribed, default: false
def execute
  if subscribed?
    # send email
  end
```

**Comment by ngan** [comment]
I see benefits either way... but just wondering what's:

1. more predictable
2. more closely aligns with Rails model predicate methods
3. less documentation to read

**Comment by tfausak** [comment]
I don't see the benefit of `foo?` over `foo` for boolean inputs. In fact, I think it makes things worse. ActiveInteraction does the exact same thing for every input type. I don't want to special case boolean inputs to define `foo?` instead of `foo`. 

I don't work at OrgSync anymore, so I can't tell you how often they use the predicate methods. I can say that it's more than never. (Maybe one of the OrgSync can help me out here. :pager: @larslevie) 

That being said, they are only a little better than the equivalent `!foo.nil?` expression. Given that they are different than what ActiveRecord provides *and* confusing with the `given?` method ActiveInteraction provides, maybe we should just get rid of them entirely. 

Can you weigh in on this, @AaronLasseigne?

**Comment by larslevie** [comment]
I ran into a situation where I assumed that ActiveInteraction's predicates worked the way ActiveRecord's do. Since they don't work the same, my feeling is they are essentially useless, and I have stopped using them.

Special casing booleans feels obviously wrong to me. If they can't behave like AR then AI should dump them entirely. That at least avoids confusion and forces the more explicit `given?`, `nil?`, etc.

**Comment by AaronLasseigne** [comment]
I'd be ok with removing them.

**Comment by tfausak** [comment]
Great! I made #398 for that. How do you feel about removing the predicates, @ngan?

**Comment by ngan** [comment]
@tfausak 👍

**Comment by AaronLasseigne** [comment]
This is in the 4.0.0 branch.
