### ISSUE TITLE
[question]Type check namespaced Object

### ISSUE THREAD

**Issue by dritir** [orgsync/active_interaction#407]
Hi, is there a way to type check a Nokogiri::XML::Document for example?

`object :"nokogiri/xml/document"
`
does not work.  The workaround was to pass the xml as string and then use nokogiri.

**Comment by tfausak** [comment]
It should work if you pass the actual class or the class name as a string or symbol.

``` rb
require 'active_interaction'
require 'nokogiri'

class Example < ActiveInteraction::Base
  object :xml_class, class: Nokogiri::XML::Document
  object :xml_string, class: 'Nokogiri::XML::Document'
  object :xml_symbol, class: :'Nokogiri::XML::Document'

  def execute
    inputs
  end
end

Example.run!(
  xml_class: Nokogiri::XML::Document.new,
  xml_string: Nokogiri::XML::Document.new,
  xml_symbol: Nokogiri::XML::Document.new)
# => {:xml_class=>#<Nokogiri::XML::Document:0x2ad85ea6e9b8 name="document">,
#     :xml_string=>#<Nokogiri::XML::Document:0x2ad85ea6e904 name="document">,
#     :xml_symbol=>#<Nokogiri::XML::Document:0x2ad85ea6e864 name="document">}
```

It doesn't work with the slashes because [`camelize`](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-camelize) converts it to `Nokogiri::Xml::Document`, which is wrong because it has `Xml` instead of `XML`.

**Comment by dritir** [comment]
Thank you, it worked like a charm.
