### ISSUE TITLE
Documentation: compose inputs vs given inputs

### ISSUE THREAD

**Issue by cloudrave** [orgsync/active_interaction#409]
I ran into an issue using compose that is probably pretty obvious to someone who's been using the framework for a while, but I thought it might be worthwhile to include it in the [composition docs](https://github.com/orgsync/active_interaction#composition).  I was thinking about something like this.

When passing `inputs` in conjunction with `import_filters` to a composed interaction, remember that those `inputs` are now considered `given?` by that interaction.  If you don't want to pass along inputs that weren't specifically given, try the following method:
```ruby
class CreateMathematician < ActiveInteraction::Base
  import_filters UpdateMathematician

  def execute
    given_inputs = inputs.select { |key| given?(key) }
    given_inputs[:mathematician] = Mathematician.new
    compose(CreateMathematician, given_inputs)
  end
end
```

This is assuming that `Add` has some optionally `nil` arguments in which you care whether that attribute is `nil`.
```ruby
class UpdateMathematician < ActiveInteraction::Base
  object :mathematician
  array :favorite_number, default: nil

  def execute
    # We want to be able to determine whether the favorite_number
    # were given by CreateMathematician.
    mathematician.favorite_number = favorite_number if given?(:favorite_number)
    mathematician
  end
end
```

**Comment by tfausak** [comment]
Oh, that is tricky. Maybe instead of adding documentation we could change how `compose` works. Instead of passing `nil` for values that weren't given, it could not pass them at all. Then `given?` would return the same thing in both interactions.

**Comment by AaronLasseigne** [comment]
@tfausak would we only do that for imported filters? I'm not sure how I feel about this. I feel like we're giving `compose` some special knowledge. Definitely going to have to think about this.

**Comment by tfausak** [comment]
Hmm, after thinking about this some more I don't think we should change how anything works. For some reason I was thinking that `compose` didn't take any arguments and instead passed everything along. If that was the case, I think it would make sense to strip out inputs that weren't given. But since you have to manually pass stuff to `compose`, it doesn't make any sense to remove `nil` values. 

I think `inputs.select(&:given?)` is a perfectly cromulent way of doing this.

**Comment by AaronLasseigne** [comment]
I've come to the same conclusion. To the original point, does this warrant a note in the docs? I haven't heard it before so I'm inclined to say no for now.

**Comment by tfausak** [comment]
We have a note about errors in composed interactions. I think it would make sense to add a short note about optional inputs as well. I'm not sure exactly what it should say, but something along the lines of:

> Composing interactions with `inputs` will pass `nil` for values that weren't given. Use something like `inputs.select(&:given?)` if you need to exclude optional inputs.

**Comment by cloudrave** [comment]
I definitely agree about not changing the functionality at all, but I do think a note in the errors section would be nice.

**Comment by cloudrave** [comment]
Also, just a note:  I don't think `inputs.select(&:given?)` works, since that would call something like `:title.given?`, right?  I think it has to be `inputs.select { |key| given?(key) }`.

**Comment by cloudrave** [comment]
Note: This may be further complicated by #410.  I'm not sure how to elegantly get nested given inputs.  I started writing a little method to do this, and it's grown to something a little ugly.  Any ideas?

**Comment by AaronLasseigne** [comment]
I'm not surprised it's getting ugly. Doing stuff like this on nested structures tends to have that effect.

We can't really suggest `inputs.select { |key| given?(key) }` because it fails to address the nested case. I don't really want to suggest it and then have a big asterisk that it doesn't work all the time. Given that this is the first we've come across it I think for now it would be best to leave the documentation alone.
