### ISSUE TITLE
compose does not copy symbolic errors

### ISSUE THREAD

**Issue by justinsteffy** [orgsync/active_interaction#87]
When using `compose` with an interaction that uses `add_sym` to create symbolic errors, the `compose` method doesn't pass these symbolic errors along to the outcome.

**Comment by tfausak** [comment]
I want to resurrect this issue for more discussion. I encountered a use case where this behavior would have been extremely useful. 

Let's say you want to refactor an interaction. It will accept the same inputs and (hopefully) return the same result, but the internals will be different. One way to accomplish this would be to create a new interaction for the refactored version and run it side-by-side with the original version. (Gems like [dat-science](https://github.com/github/dat-science) help with this part.) Since the two interactions have the same inputs, you should be able to call either of them from a top-level interaction and the errors should end up in the right place. More concretely:

``` rb
class Addition < ActiveInteraction::Base
  integer :x, :y

  def execute
    Science::Experiment.new('Addition') do |e|
      e.control { compose(AdditionControl) }
      e.candidate { compose(AdditionCandidate) }
    end.run
  end
end

class AdditionControl < ActiveInteraction::Base
  import_filters Addition

  def execute
    x + y
  end
end

class AdditionCandidate < ActiveInteraction::Base
  import_filters Addition

  def execute
    x - (-y)
  end
end
```

It looks like everything should Just Work™, but the resulting errors leave a lot to be desired.

``` rb
errors = Addition.run(x: 1, y: 'oops').errors
errors.messages
# => {:base=>["Y is not a valid integer"]}
errors.symbolic
# => {}
```

**Comment by tfausak** [comment]
I'm taking this off the v2.0.0 milestone, but it's still something that we might want to do.

**Comment by tfausak** [comment]
I am adding this to the v3.0.0 milestone. We either need to make a decision about it and fix it, or close it and commit to keeping things the way they are.
